### ISSUE TITLE
CP JavaScript blocked by server

### ISSUE THREAD

**Issue by lewyincs** [ExpressionEngine/ExpressionEngine#1491]
ExpressionEngine 6.1.5
PHP v 7.4.24
MySQL 5.6.41
Percona Server (GPL), Release 84.1

When adding a new Fluid fieldset, the fieldsets appear in the entry of the control panel as linked buttons however nothing happens when the buttons are clicked.  I also noticed that when a fluid fieldset is active on an entry, the grid fieldsets break.  When I remove the fluid fieldset from an entry, then the grid fieldsets work fine.
![fluid-field](https://user-images.githubusercontent.com/49571977/138741907-ff0f424d-3063-4684-adf3-a8c5bea7d006.jpg)

**Comment by lewyincs** [comment]
I initially installed my ee6 from scriptaculous & since upgraded to 6.1.5

Today, I decided to delete my installation of ee6 & I removed all files & database.  I manually installed a clean version of 6.1.5 from expressionengine.com.

I created new fieldset for fluid & I get the same problem - the fluid field buttons appear however they are not opening the field to edit.  It will also throw off my grid fieldsets by removing the "Add new row".

**Comment by intoeetive** [comment]
@lewyincs looking at your screenshot, seems like Grid field is not being fully initialized - you should see empty row with "No rows created" message and "Add new row" button

Can you check your browser console if it contains any Javascript errors or warnings?

**Comment by lewyincs** [comment]
Async method failed in safeAsyncMethod Error: Connection closed, pending request to server0.conn0.child4/domwalker23, type cancelPick failed

async-utils.js:59:17

**Comment by intoeetive** [comment]
I don't think EE has file with that name. Do you maybe use third-party addon that is using it?

**Comment by lewyincs** [comment]
No third-party addons.  This is a fresh install.   I just found this:

Uncaught ReferenceError: getPages is not defined
    at admin.php?/cp/publish/create/2:938

Uncaught TypeError: EE.grid is not a function
    at HTMLDocument.<anonymous> (admin.php?/cp/publish/create/2:933)
    at i (jquery.js?v=1635186749:2)
    at Object.fireWith [as resolveWith] (jquery.js?v=1635186749:2)
    at Function.ready (jquery.js?v=1635186749:2)
    at HTMLDocument.J (jquery.js?v=1635186749:2)

**Comment by intoeetive** [comment]
Does it work if you try different browser?

I would also suggest replacing all files in `/themes` from files in EE zip once again - it might be that one of the files is missing or corrupt

**Comment by lewyincs** [comment]
admin.php:1 Failed to load resource: the server responded with a status of 406 (Not Acceptable)

Yes, this is occurring in both firefox & chrome.   I will replace all /themes now.

**Comment by lewyincs** [comment]
It appears I am getting a 406 error here:

admin.php:927 

GET http://{mydomain}/admin.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/files/picker,fields/file/control_panel,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid,fields/rte/ckeditor/ckeditor,fields/rte/rte,cp/grid,fields/fluid_field/cp,cp/date_picker&v=1635345486 net::ERR_ABORTED 
406 (Not Acceptable)

**Comment by lewyincs** [comment]
I only get the 406 errors when I am trying to publish with a fluid fieldset.  All other channels are working fine.

**Comment by intoeetive** [comment]
Are you able to inspect the response in the network tab for this request?

I am interested to see if there's something that looks like error in the beginning of response body. Also request and response headers would be helpful

**Comment by lewyincs** [comment]
Request & response headers:

Request URL: http://{mydomin}/admin.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/files/picker,fields/file/control_panel,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid,fields/rte/ckeditor/ckeditor,fields/rte/rte,cp/grid,fields/fluid_field/cp,cp/date_picker&v=1635345486
Request Method: GET
Status Code: 406 Not Acceptable
Remote Address: myip:80
Referrer Policy: strict-origin-when-cross-origin

RESPONSE:
HTTP/1.1 406 Not Acceptable
Date: Wed, 27 Oct 2021 15:04:51 GMT
Server: Apache
Content-Length: 226
Keep-Alive: timeout=5, max=75
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

Failed to load response data: no data found with given resource

**Comment by intoeetive** [comment]
Ok, there must be some server error, becase the content-type is being returned as text/html and not javascript.

If you just paste the whole URL into browser address bar and visit it, what do you see? If nothing, set `$debug = 1` in admin.php and try again

**Comment by lewyincs** [comment]
Not Acceptable!

An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

**Comment by lewyincs** [comment]
![loading](https://user-images.githubusercontent.com/49571977/139135503-4a5da720-f8d2-45d6-bdf9-3b7d36053ca3.jpg)

My photo fields normally work however they break when fluid fieldset is present.

**Comment by matthewmcmullen** [comment]
@lewyincs I'm having this exact same issue! Super frustrating. Is the solution to whitelist the IP?

**Comment by matthewmcmullen** [comment]
@lewyincs mine got fixed by my host. The issue was caused due to mod security and they have disabled the rule id to resolve it.

**Comment by intoeetive** [comment]
@matthewmcmullen would your host be able to provide some insight why mod_security was blocking it in first place? E.g. what rule they had to disable

**Comment by matthewmcmullen** [comment]
@intoeetive I forgot to ask exactly what the rule was they disabled. I was just glad they fixed it. I told them to do this though: Trigger the error, make a note of the time, then find what specific rule was triggered at that time and disable it. You may end up having to disable a few rules, it depends, each server/host will be different.

**Comment by intoeetive** [comment]
@lewyincs may I ask you to test these 2 URLs:

http://{mydomin}/admin.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/files/picker,fields/file/control_panel,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid,fields/rte/ckeditor/ckeditor,fields/rte/rte,cp/grid,cp/date_picker,fields/fluid_field/cp&v=1635345486
(collects same files, but in different order)

http://{mydomin}/admin.php?S=0&D=cp&C=javascript&M=combo_load&plugin=ui.touch.punch,ee_table_reorder&file=cp/global_end,cp/files/picker,fields/file/control_panel,fields/file/file_field_drag_and_drop,fields/file/concurrency_queue,fields/file/file_upload_progress_table,fields/file/drag_and_drop_upload,fields/grid/file_grid,fields/rte/ckeditor/ckeditor,fields/rte/rte,cp/grid,cp/date_picker&v=1635345486
(excludes Fluid field file)

**Comment by lewyincs** [comment]
My host whitelisted or disabled something in mod_security & it now functions properly.  I will try to get the details of what was whitelisted and why they had it enabled.

**Comment by lewyincs** [comment]
The host whitelisted the rule ID 340029.  This rule triggers Mod Security.

**Comment by intoeetive** [comment]
Same (or similar) issue has also been reported in this thread: https://github.com/ExpressionEngine/ExpressionEngine/issues/107
